This notebook will mainly be used for the Applied Data Science Capstone Project.

In [2]:
import pandas as pd
import numpy as np

In [3]:
print("Hello Capstone Project Course!")

Hello Capstone Project Course!

## Scraping Wiki Page Table Into a Pandas Data Frame.

In [4]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'

In [5]:
df_pcodes = pd.read_html(url)

In [6]:
len(df_pcodes)

3

In [10]:
df_pcodes[0]

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

In [11]:
df_codes = df_pcodes[0]

In [12]:
df_codes.head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

## Processing the cells that have an assigned borough. Ignoring cells with a borough that is Not assigned.

In [14]:
boroughsNA = df_codes[df_codes['Borough'] == 'Not assigned'].index

In [16]:
df_codes.drop(boroughsNA , inplace=True)

In [25]:
df_codes.head()

  Postal Code           Borough                                Neighbourhood
2         M3A        North York                                    Parkwoods
3         M4A        North York                             Victoria Village
4         M5A  Downtown Toronto                    Regent Park, Harbourfront
5         M6A        North York             Lawrence Manor, Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

# Grouping all Neighborhoods by Postal Code

In [31]:
df_codes2 = df_codes.groupby('Postal Code').agg(list).reset_index()

In [39]:
df_codes2.head(20)

,Postal Code,Borough,Neighbourhood
0,M1B,[Scarborough],"[Malvern, Rouge]"
1,M1C,[Scarborough],"[Rouge Hill, Port Union, Highland Creek]"
2,M1E,[Scarborough],"[Guildwood, Morningside, West Hill]"
3,M1G,[Scarborough],[Woburn]
4,M1H,[Scarborough],[Cedarbrae]
5,M1J,[Scarborough],[Scarborough Village]
6,M1K,[Scarborough],"[Kennedy Park, Ionview, East Birchmount Park]"
7,M1L,[Scarborough],"[Golden Mile, Clairlea, Oakridge]"
8,M1M,[Scarborough],"[Cliffside, Cliffcrest, Scarborough Village West]"
9,M1N,[Scarborough],"[Birch Cliff, Cliffside West]"
10,M1P,[Scarborough],"[Dorset Park, Wexford Heights, Scarborough Tow..."
11,M1R,[Scarborough],"[Wexford, Maryvale]"
12,M1S,[Scarborough],[Agincourt]
13,M1T,[Scarborough],"[Clarks Corners, Tam O'Shanter, Sullivan]"
14,M1V,[Scarborough],"[Milliken, Agincourt North, Steeles East, L'Am..."
15,M1W,[Scarborough],"[Steeles West, L'Amoreaux West]"
16,M1X,[Scarborough],[Upper Rouge]
17,M2H,[North York],[Hillcrest Village]
18,M2J,[North York],"[Fairview, Henry Farm, Oriole]"
19,M2K,[North York],[Bayview Village]

## Replacing Not Assigned neighborhoods with their Borough instead

In [36]:
df_codes2['Neighbourhood'] = np.where(df_codes2['Neighbourhood'] == 'Not assigned', df_codes2['Borough'], df_codes2['Neighbourhood'])

In [38]:
df_codes2.head(20)

,Postal Code,Borough,Neighbourhood
0,M1B,[Scarborough],"[Malvern, Rouge]"
1,M1C,[Scarborough],"[Rouge Hill, Port Union, Highland Creek]"
2,M1E,[Scarborough],"[Guildwood, Morningside, West Hill]"
3,M1G,[Scarborough],[Woburn]
4,M1H,[Scarborough],[Cedarbrae]
5,M1J,[Scarborough],[Scarborough Village]
6,M1K,[Scarborough],"[Kennedy Park, Ionview, East Birchmount Park]"
7,M1L,[Scarborough],"[Golden Mile, Clairlea, Oakridge]"
8,M1M,[Scarborough],"[Cliffside, Cliffcrest, Scarborough Village West]"
9,M1N,[Scarborough],"[Birch Cliff, Cliffside West]"
10,M1P,[Scarborough],"[Dorset Park, Wexford Heights, Scarborough Tow..."
11,M1R,[Scarborough],"[Wexford, Maryvale]"
12,M1S,[Scarborough],[Agincourt]
13,M1T,[Scarborough],"[Clarks Corners, Tam O'Shanter, Sullivan]"
14,M1V,[Scarborough],"[Milliken, Agincourt North, Steeles East, L'Am..."
15,M1W,[Scarborough],"[Steeles West, L'Amoreaux West]"
16,M1X,[Scarborough],[Upper Rouge]
17,M2H,[North York],[Hillcrest Village]
18,M2J,[North York],"[Fairview, Henry Farm, Oriole]"
19,M2K,[North York],[Bayview Village]

In [41]:
df_codes2.shape

(103, 3)